五位学生参加了学业水平考试，7门成绩
math
english
python
chiese
art
database
physics

In [2]:
import numpy as np
names = np.array(['梁晶金','徐沁楠','朱瑞缘','王嘉瑜','郝茹馨'])#基于列表创建一维数组

In [3]:
names

array(['梁晶金', '徐沁楠', '朱瑞缘', '王嘉瑜', '郝茹馨'], dtype='<U3')

In [4]:
subject = np.array(['math','english','chinese','python','database','physics','art'])

In [5]:
subject

array(['math', 'english', 'chinese', 'python', 'database', 'physics',
       'art'], dtype='<U8')

访问一维数组

In [7]:
#数组维度
names.ndim 

1

In [8]:
#数组元素个数
names.size

5

In [9]:
#数组数据类型
names.dtype

dtype('<U3')

In [10]:
names[2]#数组索引

'朱瑞缘'

In [11]:
subject[6]#数组索引

'art'

数组切片

In [12]:
names[[0,2,4]]#抽取数组下标为0,2,4的元素

array(['梁晶金', '朱瑞缘', '郝茹馨'], dtype='<U3')

In [13]:
names[0:2]#抽取数组下标0~1的元素

array(['梁晶金', '徐沁楠'], dtype='<U3')

In [16]:
subject[:-1:2]#Star : End : Step，表示从开头到倒数第二个元素之间抽取，步长为2

array(['math', 'chinese', 'database'], dtype='<U8')

In [18]:
names[(names == '梁晶金')|(names == '徐沁楠')] #筛选出名为梁晶金和徐沁楠的同学

array(['梁晶金', '徐沁楠'], dtype='<U3')

In [19]:
judge = (names == '梁晶金') | (names == '徐沁楠') #生成Bool型数组

In [20]:
judge

array([ True,  True, False, False, False])

In [25]:
#创建二维数组
scores = np.array([[70,85,77,90,82,84,89],
                  [60,64,80,75,80,92,90],
                  [90,90,88,87,86,90,91],
                  [80,82,91,95,88,83,86],
                  [88,72,78,90,91,73,80]
                  ])

In [26]:
scores

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90],
       [90, 90, 88, 87, 86, 90, 91],
       [80, 82, 91, 95, 88, 83, 86],
       [88, 72, 78, 90, 91, 73, 80]])

In [44]:
#筛选二维数组元素
scores[(names == '梁晶金') | (names == '徐沁楠')]

array([[70, 85, 77, 90, 82, 84, 89],
       [60, 64, 80, 75, 80, 92, 90]])

In [46]:
#想提取出梁晶金和徐沁楠的math和python课成绩
scores[(names == '梁晶金') |(names == '徐沁楠')][:,(subject == 'math')|(subject == 'python')]

array([[70, 90],
       [60, 75]])

In [ ]:
#访问二维数组

In [28]:
#查看二维数组的维数
scores.ndim

2

In [29]:
#查看二维数组的元素个数
scores.size

35

In [30]:
#查看数组的行数和列数
scores.shape

(5, 7)

In [31]:
#查看数组的元素类型
scores.dtype

dtype('int32')

In [ ]:
#二维数组切片 arr[row:column]，行不能省略，列可以省略

In [32]:
scores[0,0] #提取数组的第0行第0列那个元素

70

In [34]:
scores[[1,3],[2,4]]

array([80, 88])

In [35]:
 scores[:,[0,1]] #抽出所有行的第0列和第1列元素

array([[70, 85],
       [60, 64],
       [90, 90],
       [80, 82],
       [88, 72]])

In [37]:
scores[[1,3]] #抽取第1行和第3行元素值

array([[60, 64, 80, 75, 80, 92, 90],
       [80, 82, 91, 95, 88, 83, 86]])

In [38]:
scores[[0,3],1:4] #抽取第0行和第3行中，第1列~第3列数据值

array([[85, 77, 90],
       [82, 91, 95]])

In [40]:
scores[0:3,1:4] ##抽取第0行到第3行，中第1列~第3列数据值

array([[85, 77, 90],
       [64, 80, 75],
       [90, 88, 87]])

In [41]:
scores[[1,3]][:,[0,1]] #两层切片，先抽取第一行和第三行元素，再抽取其中的第0列和第1列元素

array([[60, 64],
       [80, 82]])

In [42]:
 scores[[1,3],0:2] #与上面双层切片等价

array([[60, 64],
       [80, 82]])

In [48]:
#创建和初始化多维数组
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
np.arange(3,11,2)

array([3, 5, 7, 9])

In [51]:
np.arange(0.3,1.5,0.3) #生成浮点数列

array([0.3, 0.6, 0.9, 1.2])

In [52]:
np.arange(0,15).reshape(3,5) #将一维数组重建为制定多维数组

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
np.zeros((3,4)) #建一个全为0的数组

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.ones((3,4)) #建一个全为1的数组

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

练习题
1、在subjects数组中选择并显示序号1、2、4门课的名称，使用负值序号选择并显示names数组中 '梁晶金'。

In [60]:
subject[[1,2,4]] #选择序号为1,2,4的课

array(['english', 'chinese', 'database'], dtype='<U8')

In [62]:
names[:-4]

array(['梁晶金'], dtype='<U3')

练习题
2、选择并显示names数组从2到最后的数组元素；选择并显示subjects数组2到4的数组元素。

In [64]:
names[2:]

array(['朱瑞缘', '王嘉瑜', '郝茹馨'], dtype='<U3')

In [65]:
subject[2:]

array(['chinese', 'python', 'database', 'physics', 'art'], dtype='<U8')

练习题
使用布尔条件选择并显示subjects数组中的英语和物理科目名称。

In [66]:
subject[(subject == 'physics')|(subject == 'english')]

array(['english', 'physics'], dtype='<U8')

In [69]:
judge2 = (subject =='physics') | (subject == 'english') 

In [70]:
judge2

array([False,  True, False, False, False,  True, False])

二维数组练习题
1、选择并显示scores数组的1、4行。
2、选择并显示scores数组中行号2、4同学的数学和Python成绩。

In [72]:
scores[[1,4]]

array([[60, 64, 80, 75, 80, 92, 90],
       [88, 72, 78, 90, 91, 73, 80]])

In [74]:
scores[[2,4]][:,[0,3]]

array([[90, 87],
       [88, 90]])

二维数组练习题
3、选择并显示scores数组中所有同学的数学和艺术课程成绩。
4、选择并显示scores数组中“朱瑞缘”和“郝茹馨”的英语和艺术课程成绩。

In [76]:
scores[:,[0,6]]

array([[70, 89],
       [60, 90],
       [90, 91],
       [80, 86],
       [88, 80]])

In [77]:
scores[[0,4]][:,[1,6]]

array([[85, 89],
       [72, 80]])

3、生成由整数10~19组成的2×5的二维数组。

In [78]:
arr = np.arange(10,20).reshape(2,5)

In [79]:
arr

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])